version: '3.5'
services:
  myspa:
    build: .
    ports:
     - '8000:4200'
    volumes:
      - "/app/node_modules"
      - ".:/app"

  # nginx:
  #   image: nginx:latest
  #   ports:
  #    - '8000:8000'
  #   volumes:
  #     - "/app/node_modules"
  #     - ".:/app"

  # app.web:
  #   build:
  #     context: .
  #     args:
  #       env: prod
  #   ports:
  #     - '4201:4200'
    